name: external_dependencies
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5
  go_router: ^14.1.4
  intl: ^0.19.0
  stack_trace: ^1.11.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
